import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../services/database/repositories/meeting_repository.dart';
import '../../../../core/extensions/date_extensions.dart';
import 'package:add_2_calendar/add_2_calendar.dart';

class MeetingDetailScreen extends ConsumerWidget {
  final String id;
  const MeetingDetailScreen({super.key, required this.id});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final colors = theme.colorScheme;
    final meetings = ref.watch(allMeetingsProvider);

    return meetings.when(
      data: (items) {
        final meeting = items.where((m) => m.id == id).firstOrNull;
        if (meeting == null) return Scaffold(appBar: AppBar(), body: const Center(child: Text('Meeting not found')));

        return Scaffold(
          appBar: AppBar(title: Text(meeting.title), actions: [
            IconButton(icon: const Icon(Icons.edit_calendar_outlined), onPressed: () {
              final event = Event(
                title: meeting.title,
                description: meeting.agenda ?? 'Meeting generated by FounderOS',
                location: '',
                startDate: meeting.date,
                endDate: meeting.date.add(const Duration(minutes: 60)),
                iosParams: const IOSParams(reminder: Duration(minutes: 15)),
              );
              Add2Calendar.addEvent2Cal(event);
            }),
            IconButton(icon: const Icon(Icons.edit_outlined), onPressed: () {
              context.push('/meetings/create', extra: meeting);
            }),
            IconButton(icon: const Icon(Icons.delete_outline), onPressed: () {
              ref.read(meetingRepositoryProvider).delete(id);
              ref.invalidate(allMeetingsProvider);
              Navigator.pop(context);
            }),
          ]),
          body: SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              // Header info
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(color: colors.primaryContainer.withValues(alpha: 0.2), borderRadius: BorderRadius.circular(14)),
                child: Row(children: [
                  Icon(Icons.event, color: colors.primary),
                  const SizedBox(width: 12),
                  Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Text(meeting.date.formattedDay, style: theme.textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.w600)),
                    Text(meeting.date.formattedTime, style: theme.textTheme.bodySmall),
                  ]),
                  const Spacer(),
                  Chip(label: Text(meeting.type, style: const TextStyle(fontSize: 12))),
                ]),
              ),
              const SizedBox(height: 20),
              if (meeting.clientName != null) ...[
                _Section(title: 'Client', content: meeting.clientName!),
              ],
              if (meeting.agenda != null && meeting.agenda!.isNotEmpty) ...[
                _Section(title: 'Agenda', content: meeting.agenda!),
              ],
              if (meeting.participants.isNotEmpty) ...[
                Text('Participants', style: theme.textTheme.titleSmall?.copyWith(fontWeight: FontWeight.w700)),
                const SizedBox(height: 8),
                Wrap(spacing: 8, children: meeting.participants.map((p) => Chip(avatar: CircleAvatar(radius: 12, child: Text(p[0].toUpperCase(), style: const TextStyle(fontSize: 10))), label: Text(p, style: const TextStyle(fontSize: 12)))).toList()),
                const SizedBox(height: 16),
              ],
              if (meeting.notes != null && meeting.notes!.isNotEmpty) _Section(title: 'Notes', content: meeting.notes!),
              if (meeting.actionItems.isNotEmpty) ...[
                Text('Action Items', style: theme.textTheme.titleSmall?.copyWith(fontWeight: FontWeight.w700)),
                const SizedBox(height: 8),
                ...meeting.actionItems.map((item) => Padding(
                  padding: const EdgeInsets.only(bottom: 8),
                  child: Row(children: [
                    Icon(Icons.check_circle_outline, size: 18, color: colors.primary),
                    const SizedBox(width: 8),
                    Expanded(child: Text(item, style: theme.textTheme.bodyMedium)),
                  ]),
                )),
                const SizedBox(height: 16),
              ],
              if (meeting.requirements != null) _Section(title: 'Requirements', content: meeting.requirements!),
              if (meeting.decisions != null) _Section(title: 'Decisions', content: meeting.decisions!),
              if (meeting.followUps.isNotEmpty) ...[
                Text('Follow-ups', style: theme.textTheme.titleSmall?.copyWith(fontWeight: FontWeight.w700)),
                const SizedBox(height: 8),
                ...meeting.followUps.map((f) => Padding(
                  padding: const EdgeInsets.only(bottom: 8),
                  child: Row(children: [Icon(Icons.arrow_right, size: 18), const SizedBox(width: 4), Expanded(child: Text(f))]),
                )),
              ],
            ]),
          ),
        );
      },
      loading: () => Scaffold(appBar: AppBar(), body: const Center(child: CircularProgressIndicator())),
      error: (e, _) => Scaffold(appBar: AppBar(), body: Center(child: Text('Error: $e'))),
    );
  }
}

class _Section extends StatelessWidget {
  final String title; final String content;
  const _Section({required this.title, required this.content});
  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(padding: const EdgeInsets.only(bottom: 16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Text(title, style: theme.textTheme.titleSmall?.copyWith(fontWeight: FontWeight.w700)),
      const SizedBox(height: 8),
      Text(content, style: theme.textTheme.bodyMedium),
    ]));
  }
}
